ALTER TABLE boletos DROP COLUMN cod_vuelo;
ALTER TABLE boletos DROP COLUMN rut_pasajero;

ALTER TABLE vuelo ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE pasajero ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;