ALTER TABLE vuelo ADD COLUMN habilitado TINYINT NOT NULL DEFAULT 1;
ALTER TABLE pasajero ADD COLUMN habilitado TINYINT NOT NULL DEFAULT 1;
ALTER TABLE boleto ADD COLUMN habilitado TINYINT NOT NULL DEFAULT 1;